configurable tours
cernbox/web pull request #130
Opened 2022-05-19 11:55 UTC by elizavetaRa

## Description
- added option to create tours

2022-05-20 08:54 UTC, diocas requested changes
I have the impression this should not be mingled with web-runtime and instead we should have it as a separate extension. Wouldn't this be possible? I think the separation of concerns would be much more clear.
I guess the issue is knowing when we move between views? I believe web doesn't have - but maybe it should - a notifications paradigm, where we can set listeners that subscribe to changes that occur in the system... Would be a good thing to propose, I guess.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/tours/new.json
> +{
Please remove this from the PR upstream and put it a new "app" in our web-extensions

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/tours/test.json
> +{
Not sure we can push it upstream, maybe yes, but at least make it "welcome to owncloud" and put some example messages that have nothing to do with cernbox.

2022-05-20 08:54 UTC, diocas commented on packages/web-pkg/src/helpers/buffer.js
> +/**
Is this a leftover from a rebase?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/App.vue
> +        if (this.toursCurrentLanguage.length > 0) autostartTours(this.toursCurrentLanguage, to.name)
If you set the language in bellow's action, why do you still need to pass it every time you call autostart?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/App.vue
> +          if (this.toursCurrentLanguage.length > 0) this.setToursCurrentLanguage()
You already have a language code here, why are you still trying to get it within `setToursCurrentLanguage`? I guess this gets called in a different place where this is not provided, but do we really need to do it then?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/components/Topbar/TopBar.vue
> +    isLightweight() {
this should not be here...

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/components/Topbar/TopBar.vue
> +    toursAllowed() {
Since we added the possibility to specify the views where we want a tour to be displayed, do we still need to check this? Maybe we should assume that we let the tour decide if it wants to be shown in a public link or not, even if it doesn't make too much sense (and especially since we don't have the user prefs persisted).

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/components/Topbar/TopBar.vue
> +    toursAllowed() {
Also, shouldn't all tours logic be in the tours stuff (namely in Tours.vue)? It doesn't seem well organized to have things in the topbar. Instead you could call a method defined somewhere else, I guess.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      v-oc-tooltip="'aa'"
aa?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +        <translate>Tours</translate> </oc-button
In the past they've asked us to replace these translate tags, didn't they?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/components/Topbar/TopBar.vue
> +      <tours v-if="toursAllowed" />
Can't you remove the if from here and just do it from inside the tour component itself? This would make the changes here much simpler.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +  <div id="tours">
The if would be here

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/container/bootstrap.ts
> +  const { tours } = await loadTours(runtimeConfiguration?.tours)
Why is this inside announce theme if it has nothing to do with it? Please call it in the index, where announcetheme is also called.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/container/bootstrap.ts
> +  const { tours } = await loadTours(runtimeConfiguration?.tours)
You might even have the language there, which means you don't need to check it in `setToursCurrentLanguage`, as I mentioned before.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/helpers/tours.js
> +export const loadTours = async (locations = []) => {
The naming "locations" is confusing. So much so I was going to write something else in this comment because I imagined you were doing other assumptions.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/helpers/tours.js
> +    if (l.split('.').pop() === 'json') {
is it really necessary this if?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/helpers/tours.js
> +  return { tours: tours }
`{tours}` would be the same, no?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/helpers/tours.js
> +  return 'autostart1'
why this return?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +  tours: {},
maybe would call it "allTours" and "enabled/currentTours" our just "tours"?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +    const language = document.documentElement.lang || 'en'
as mentioned in previous messages, I would pass the language as parameter, since we should have it from the callers.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +    const translatedTour = t[language] ? t[language] : t.en
What if we don't have en? I think we're assuming the default is en and everyone will have a tour in that language, but I wonder if it's true (I can see people using diff languages on their UI and then prepare tours on it, even if the user picks some other language for them). I would, at least, check if there is an en or, not so sure but maybe valid, pick the first language tour in the list?

Scenario: a french company deploys oc, sets their default to french and puts their tours in french as well. I chose english as my language... Maybe I should still see the tour?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +      useModalOverlay: translatedTour.useModalOverlay ? translatedTour.useModalOverlay : false,
`translatedTour.useModalOverlay === True`?
Same for others bellow.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +        classes: translatedTour.defaultStepOptions?.classes
`translatedTour.defaultStepOptions?.classes || []`?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +      useModalOverlay: translatedTour.useModalOverlay ? translatedTour.useModalOverlay : false,
`translatedTour.useModalOverlay === True`?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +  buttons.includes('Learn more') &&
give it a tag, not a full name with spaces, like we discussed last week.

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +  if (buttons.includes('back') || buttons.includes('Back'))
lowercase + includes?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +  if (buttons.includes('back') || buttons.includes('Back'))
same bellow

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +      text: 'Learn more',
Translate?

2022-05-20 08:54 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +      useModalOverlay: translatedTour.useModalOverlay ? translatedTour.useModalOverlay : false,
`translatedTour.useModalOverlay === True`?

2022-05-24 12:52 UTC, javfg commented
> I have the impression this should not be mingled with web-runtime and instead we should have it as a separate extension. Wouldn't this be possible? I think the separation of concerns would be much more clear. I guess the issue is knowing when we move between views? I believe web doesn't have - but maybe it should - a notifications paradigm, where we can set listeners that subscribe to changes that occur in the system... Would be a good thing to propose, I guess.

Is it possible for a web extension to inject content into another? I'm looking on how to do this. I'm not sure I understand how the scaffolding of this works, but I see in web extensions you specify a route for the extension to be available. Maybe they can only live in their own paths.

Also if `files` is already an extension, and the tour is basically to show how to use it, wouldn't it make more sense to be put inside of it?

2022-05-25 17:16 UTC, diocas commented
I don't think there's a way to inject it now, but I would be surprised if they didn't had it in the future (especially to inject things in the top bar menu). So I think we can prepare for it now. But let's discuss it with owncloud.

To the other extension, can we assume the tours will be for files only? Or will this be a more generic thing?

2022-06-01 07:38 UTC, diocas commented
@elizavetaRa let us know when it's ready for a re-review

2022-06-03 07:48 UTC, elizavetaRa commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +        <translate>Tours</translate> </oc-button
They use them all over the app in all the buttons with texts

2022-06-03 07:50 UTC, elizavetaRa commented on packages/web-runtime/src/helpers/tours.js
> +export const loadTours = async (locations = []) => {
consistent with packages/web-runtime/src/helpers/theme.js, where they fetch json from "location"

2022-06-03 07:51 UTC, elizavetaRa commented on packages/web-runtime/src/helpers/tours.js
> +    if (l.split('.').pop() === 'json') {
consistent with packages/web-runtime/src/helpers/theme.js, they also do a check if the file is a json

2022-06-03 08:31 UTC, elizavetaRa commented on packages/web-runtime/src/App.vue
> +        if (this.toursCurrentLanguage.length > 0) autostartTours(this.toursCurrentLanguage, to.name)
I pass tours in current language and route name if route changed

2022-06-03 15:37 UTC, javfg requested changes

2022-06-03 15:37 UTC, javfg commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +        <translate>Tours</translate> </oc-button
That closing `oc-button` tag should probably go into a newline.

2022-06-03 15:37 UTC, javfg commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +}
Is there any way to avoid setting all the styles as `!important`? That can be painful in the future.

2022-06-03 15:37 UTC, javfg commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      })
```suggestion
      const toursAllowed = this.tours.some(t => this.tourAllowed(t))
```

2022-06-03 15:37 UTC, javfg commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      if (tour.allowLocations?.length > 0) return tour.allowLocations.includes(this.$route.name)
I think you can skip the length here check and use something like:

```
if (tour.allowLocations?.includes(this.$route.name)) return true
```
And similar for the one below for `denyLocations`.

2022-06-03 15:37 UTC, javfg commented on packages/web-runtime/tours/example_tour.json
> +{     "translations": {      "en": {
You should reformat this one.

2022-06-03 15:37 UTC, javfg commented on packages/web-runtime/src/store/tours.js
> +  tours.forEach((t, i) => {
You are not using the index, right?

2022-06-03 15:55 UTC, diocas reviewed
Some comments. Let's push it and see what they say.. (there are things I don't really understand, so it's better that more knowledgeable eyes take a look).
We will eventually have to improve a bit the look and feel (but at least now is consistent with the rest of the elements).

2022-06-03 15:55 UTC, diocas commented on packages/web-runtime/src/App.vue
> +        if (this.toursCurrentLanguage.length > 0) autostartTours(this.toursCurrentLanguage, to.name)
But why? What's the difference? What makes a tour with autostart different from the others, language wise?
My point was also: can't you find the language without having to inject this here?

2022-06-03 15:55 UTC, diocas commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      <oc-button id="toursButton" v-oc-tooltip="'See tours through the interface'" size="small">
Translate tooltip?

2022-06-03 15:55 UTC, diocas commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      isPublicLocation: useActiveLocation(isLocationPublicActive, 'files-public-files')
I think this is why I always see the tour when I open a file in a public link. Technically is not the files app public files route, so... We need to set this properly in our config!

2022-06-03 15:55 UTC, diocas commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      return toursAllowed
```js
this.tours.forEach((t) => {
    if (this.tourAllowed(t)) return true
})
return false
```

Or even better:

```js
return this.tours.some(t => this.tourAllowed(t))
```
^^^ with this one you don't even need `if (this.tours.length === 0) return false`...

2022-06-03 15:55 UTC, diocas commented on packages/web-runtime/src/container/bootstrap.ts
> +  await store.dispatch('setToursCurrentLanguage', 'en')
Hardcoded value for en

2022-06-03 15:55 UTC, diocas commented on packages/web-runtime/src/store/tours.js
> +  tours.forEach((t, i) => {
do you even use the index?

2022-06-03 15:56 UTC, diocas commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      })
Dude..

2022-06-06 14:35 UTC, elizavetaRa commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +        <translate>Tours</translate> </oc-button
it's formating by `yarn fix lint`

2022-06-07 07:05 UTC, diocas commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      return toursAllowed
did you read my last comment?

2022-06-07 12:17 UTC, elizavetaRa commented on packages/web-runtime/src/App.vue
> +        if (this.toursCurrentLanguage.length > 0) autostartTours(this.toursCurrentLanguage, to.name)
I mean, this was not the language that I pass but the translated to current language tours. I renamed the variable to "translatedTours"

2022-06-08 06:47 UTC, closed without merging

2022-06-08 07:20 UTC, elizavetaRa commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +}
A big weak point of this library: the classes are hard-coded into shepherd.js and need to be overwritten, which doesn't work without `!important`. Adding own classes is very limited. Moreover, they are added before shepherd classes and get less priority. I'll check on the possibility to inject classes dynamically by getting the elements by class.

2022-06-08 07:22 UTC, elizavetaRa commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +      if (tour.allowLocations?.length > 0) return tour.allowLocations.includes(this.$route.name)
here the logic is different: if there is `allowLocations` property and it has some elements, allow/deny based on it. If no `allowLocations`, check `denyLocations` and return based on it.

2022-06-08 07:53 UTC, javfg commented on packages/web-runtime/src/components/Topbar/Tours/Tours.vue
> +}
I see. Maybe you can use the custom class parameter [shown in the docs](https://shepherdjs.dev/docs/tutorial-03-styling.html), but I'm not sure how well it will play with Vue.