Imageselector
cernbox/web pull request #163
Opened 2023-06-29 09:20 UTC by johafr

## Description
It is now possible to filter the different filetypes in webappfiles.

2023-06-30 13:32 UTC, elizavetaRa commented on packages/design-system/src/components/OcPageSize/OcPageSize.vue
> +  <div class="oc-page-size" :style="{ justifyContent: alignment }">
Please try to rather user css classes than inline styles

2023-06-30 13:34 UTC, elizavetaRa commented on packages/design-system/src/components/OcPageSize/OcPageSize.vue
> +    alignment: {
Please add comments similar to other props. Otherwise it's not clear why it's there and what is the purpose

2023-06-30 14:50 UTC, elizavetaRa commented on pnpm-lock.yaml
> +settings:
Avoid modifications in pnpm-lock

2023-06-30 14:54 UTC, elizavetaRa commented on packages/web-pkg/src/composables/filters/constants.ts
> +  static readonly resourceOptions = ['No filter', 'Images', 'Textfiles', 'Folders', 'Scripts']
The options need to be properly translated, check $gettext function that is aplied for translatable strings. No need to provide translations

2023-06-30 15:10 UTC, elizavetaRa commented on packages/web-pkg/src/components/ViewOptions.vue
> +          <oc-text-input
As mentioned technically good implementation but regarding the usability:
- Filter by search field requires recall rather than recognition, bad practice
- I think it's a bit overcomplicated, simple filter by file type image/video/audio.... would be enough :)

2023-06-30 15:12 UTC, elizavetaRa requested changes
See comments

2023-07-03 13:39 UTC, johafr commented on packages/web-pkg/src/composables/filters/constants.ts
> +  static readonly resourceOptions = ['No filter', 'Images', 'Textfiles', 'Folders', 'Scripts']
It is now translated in ViewOptions line 171 as the datatype not static :)

2023-08-07 12:32 UTC, closed without merging